antora:
  extensions:
    - require: '@springio/antora-extensions'
      root_component_name: 'integration'

site:
  title: Spring Integration
  url: https://docs.spring.io/spring-integration/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-integration
    # Refname matching:
    # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
    branches: [ main,'({6..9}).+({0..9}).x', '!(6.{0..1}.x)' ]
    tags: [ 'v({6..9}).+({0..9}).+({0..9})?(-{RC,M}+({0..9}))', '!(v6.{0..1}.+({0..9})?(-{RC,M}+({0..9})))', '!(v6.2.0-M1)', '!(v6.2.0-M2)' ]
    start_path: src/reference/antora
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-integration
    page-related-doc-categories: security
    page-related-doc-projects: batch,framework,integration,amqp,kafka
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.15/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
